### ISSUE TITLE
Open chatgpt-raycast using hotkey

### ISSUE THREAD

**Issue by romanpeters** [abielzulio/chatgpt-raycast#1]
I assigned a hotkey to the chatgpt plugin in the Raycast settings.
However when I trigger it using the hotkey I get this error (presumably because it sends the question without input):
```
TypeError: Cannot read properties of undefined (reading 'length')
Main:ask.tsx:11:47
```
```
 8: }
 9: 
10: export default function Main(props: { arguments: Arguments }) {
11:   const [answer, setAnswer] = useState<string>("");
                                                  ^
12:   const [isLoading, setIsLoading] = useState<boolean>(true);
13: 
14:   const { question } = props.arguments;

Main:ask.tsx:11:47
zt:index.js:5:2490
    at ray-navigation-stack
Rr:index.js:5:2088
```

Is it possible to assign the plugin to a hotkey, while still allowing to input a question, without error?

**Comment by abielzulio** [comment]
This is something that I'm currently working on!

At the moment, I'm still refactoring the codebase. Looking for another type of input for a better user experience and then will add the requested features one by one. Do you think the current way of taking your input is pleasing or not?

**Comment by abielzulio** [comment]
https://user-images.githubusercontent.com/7030944/205548394-6f2701a2-270b-469c-ae0e-9227a596b7e5.mp4


This required extra steps but should allow users to assign a custom shortcut to the "ask" command. What do you think @romanpeters?

**Comment by abielzulio** [comment]
https://github.com/abielzulio/chatgpt-raycast/commit/3b84117102b5e0cf6d397718a589c084e64875ad Pushed the update so you can try @romanpeters

**Comment by abielzulio** [comment]
Should've been able to be assigned to a hotkey. Let me know if it isn't, closing it now.

**Comment by romanpeters** [comment]
That was quick! 
This looks great, thanks!
