### ISSUE TITLE
Build not building to /dist? 

### ISSUE THREAD

**Issue by altryne** [abielzulio/chatgpt-raycast#10]
Hey, super cool! Thanks for the work. 

I'm new to raycast extensions, running `npm run build` which is supposed to... create a dist folder no? 

The build command says `built succesfully` but no /dist folder ,and raycast says it can't find any?

**Comment by 1Yanik3** [comment]
you have to run `npm run dev`, not build it

**Comment by neoromantic** [comment]
so, for now, I have to have it up&running in dev mode to be able to use it in Raycast?

**Comment by abielzulio** [comment]
> so, for now, I have to have it up&running in dev mode to be able to use it in Raycast?

For now, yes. I'm still working on some requested features then I'll submit it to the store.
