### ISSUE TITLE
ChatGPT falied auth token

### ISSUE THREAD

**Issue by marxo126** [abielzulio/chatgpt-raycast#11]
I've followed the instructions and I've updated the latest version of ChatGPT-api from transitive-bullshit and it still shows me the problem you see in the screenshoot. How do I do it now? Should I wait until you update this chatgpt-raycast? Thank you.

![Screenshot 2022-12-18 at 11 33 22](https://user-images.githubusercontent.com/4749548/208293523-428cae61-df5f-4513-ac42-d76dd2cee34a.jpg)
![Screenshot 2022-12-18 at 11 33 37](https://user-images.githubusercontent.com/4749548/208293524-87da52fc-c978-4fa7-923a-0fccc44769b4.jpg)

**Comment by abielzulio** [comment]
> I've followed the instructions and I've updated the latest version of ChatGPT-api from transitive-bullshit and it still shows me the problem you see in the screenshoot. How do I do it now? Should I wait until you update this chatgpt-raycast? Thank you.
> 
> 
> 
> ![Screenshot 2022-12-18 at 11 33 22](https://user-images.githubusercontent.com/4749548/208293523-428cae61-df5f-4513-ac42-d76dd2cee34a.jpg)
> 
> ![Screenshot 2022-12-18 at 11 33 37](https://user-images.githubusercontent.com/4749548/208293524-87da52fc-c978-4fa7-923a-0fccc44769b4.jpg)

Hi,

Please don't update anything manually by yourself. I'm still figuring out a way to be able to utilize the new API as it won't build. I've contacted both the API author and the raycast dev but still have no idea yet why the new API won't build. Will let you know how it's going.

**Comment by abielzulio** [comment]
Closed due to the new OpenAI's ChatGPT API, now the extension is getting alive again.
