### ISSUE TITLE
Multiple Q&A support

### ISSUE THREAD

**Issue by DottChen** [abielzulio/chatgpt-raycast#15]
Great work here! I'm wondering if there is going to be a multiple Q&A support in the future that uses the turbo API? Would be really useful to have that, and could be a replacement for the original ChatGPT client.

**Comment by abielzulio** [comment]
> Great work here! I'm wondering if there is going to be a multiple Q&A support in the future that uses the turbo API? Would be really useful to have that, and could be a replacement for the original ChatGPT client.

Already working on it! Once it's done, I'm going to publish it to the extension store. Hang on!

**Comment by DottChen** [comment]
> > Great work here! I'm wondering if there is going to be a multiple Q&A support in the future that uses the turbo API? Would be really useful to have that, and could be a replacement for the original ChatGPT client.
> 
> Already working on it! Once it's done, I'm going to publish it to the extension store. Hang on!

Great!

**Comment by abielzulio** [comment]
Multiple Q&A is here! @DottChen

**Comment by DottChen** [comment]
Excellent! Thank you!
