### ISSUE TITLE
Are you suggesting that I install it from the store? Because I can't seem to find it.

### ISSUE THREAD

**Issue by OpheliaAshworth** [abielzulio/chatgpt-raycast#27]

**Comment by rodrigo398** [comment]
It seems it's still under review?
[This extension is under Raycast's review (https://github.com/raycast/extensions/pull/5253)](https://github.com/abielzulio/chatgpt-raycast/commit/d1ff48e39626284d8be278cd301e4d78b6019662)

**Comment by malcommac** [comment]
could I install it manually?

**Comment by EnixCoda** [comment]
To install it before it is available from the store, try the `import extension` command, choose the downloaded & extracted ZIP of this repo.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/7480839/227880768-8d254c1b-28e8-4b9a-91e3-bfcc34e37bda.png">

**Comment by abielzulio** [comment]
Closed due to its availability in the store.

<a title="Install chatgpt Raycast Extension" href="https://www.raycast.com/abielzulio/chatgpt"><img src="https://www.raycast.com/abielzulio/chatgpt/install_button@2x.png" style="height: 64px;" alt="" height="64"></a>
