### ISSUE TITLE
429 error with Store version

### ISSUE THREAD

**Issue by eurunuela** [abielzulio/chatgpt-raycast#30]
Hi there,

I cannot seem to use the plugin, as I get a 429 error every time I submit a promt.

**Comment by abielzulio** [comment]
> Hi there,
> 
> 
> 
> I cannot seem to use the plugin, as I get a 429 error every time I submit a promt.

Hi! Have you tried to take a look at this? What kind of prompt you are trying to ask?

https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

**Comment by eurunuela** [comment]
I guess the issue is I'm on the free plan. Thank you!
