### ISSUE TITLE
Seems extension haven't used the API key and there's errors shown

### ISSUE THREAD

**Issue by stillnaughty** [abielzulio/chatgpt-raycast#31]
I download the extension today and specify my account OpenAI key in the preference (which is already subscribed for ChatGPT plus)

But turn out:
- when I specify use of GPT-4 it shows GPT-4 is not supported
- If not specified it shows error 429
- my API key has shown the key is never used in my OpenAI account interface.

Guess the extension have not used the API key specified and would you mind looking into the problems and see if this is the case?
Thanks

**Comment by abielzulio** [comment]
> I download the extension today and specify my account OpenAI key in the preference (which is already subscribed for ChatGPT plus)
> 
> But turn out:
> 
>     * when I specify use of GPT-4 it shows GPT-4 is not supported
> 
>     * If not specified it shows error 429
> 
>     * my API key has shown the key is never used in my OpenAI account interface.
> 
> 
> Guess the extension have not used the API key specified and would you mind looking into the problems and see if this is the case? Thanks

Hi! I've updated the extension so now it's able to provide the model list based on your account support. Please let me know how it's going.

**Comment by stillnaughty** [comment]
Thanks... so.. .did the GPT-4 has been removed for the new release? can't see the option there.
Mind asking is there any reasons behind that GPT-4 can't be supported at the time? thanks

**Comment by stillnaughty** [comment]
btw... .still error 429 on using GPT-3 for me... but key is used that shown in the OpenAI page unlike the last time just for your information

**Comment by abielzulio** [comment]
> Thanks... so.. .did the GPT-4 has been removed for the new release? can't see the option there. Mind asking is there any reasons behind that GPT-4 can't be supported at the time? thanks

You can't see the GPT-4 option because your developer account isn't supported. Could you give me a screenshot of your 429 error?

**Comment by stillnaughty** [comment]
Thanks.. but.. how could I get the developer account btw? I've subscribed OpenAI plus already and get my API key thro https://platform.openai.com/account/api-keys, and that should be GPT-4 supported indeed.  Is there anything wrong for the procedure?

Meanwhile attached pls find the following screenshot.  Cheers
![Screenshot 2023-03-29 at 5 57 07 PM](https://user-images.githubusercontent.com/2071113/228613316-a56ad46a-14fc-42a0-919a-1492ccc12820.png)

**Comment by dominiquejb** [comment]
I'm getting the same 429 error as @stillnaughty

**Comment by abielzulio** [comment]
Subscribing to the plus doesn't mean you can get the GPT-4 access with your API key. You need to join their GPT-4 waitlist first to be able to have that access. I'm already on their waitlist but still couldn't get their access yet.

Could you give me a screenshot of what your custom model settings lookalike? @stillnaughty @dominiquejb

**Comment by Paranoid-Dev** [comment]
@abielzulio I'm using a free account and I get error 429 every time I try to use it (on the default settings/model when downloaded from the store). 
Is this not available for use with free accounts? A quick googling tells me error 429 is a rate limiting error but I haven't used chatgpt once in this timeframe so I should not be rate limited.

**Comment by abielzulio** [comment]
> @abielzulio I'm using a free account and I get error 429 every time I try to use it (on the default settings/model when downloaded from the store). Is this not available for use with free accounts? A quick googling tells me error 429 is a rate limiting error but I haven't used chatgpt once in this timeframe so I should not be rate limited.

Hi! Could you try this PR (https://github.com/raycast/extensions/pull/5725) version?

**Comment by Spiteless** [comment]
Hello,

I'm also having this issue. I just signed up after hearing about this extension on the Syntax podcast. Set up the API key as per instructions and immediately got 429 error.

UPDATE:

Above you mentioned `pay-as-you-go` might work, I just upgraded to a paid account, rerolled my api key, and then it worked:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/5898009/230277857-f6440e50-1d1b-444b-964d-b63949a9414a.png">

**Comment by Paranoid-Dev** [comment]
I am of the opinion that free accounts should also work unless they made more requests than are allowed in a certain timeframe since we can use them just fine on the website. But maybe some api points are paid accounts only? That would explain rate limiting despite never having used openai in that timeframe.
