### ISSUE TITLE
When issuing new questions in the same conversation, only the response to #1 is remembered

### ISSUE THREAD

**Issue by mike-hearn** [abielzulio/chatgpt-raycast#33]
Example:

Q: What's 1 + 1?
A: 2
Q: Add 1 to that
A: The result of adding 1 to 2 is 3.
Q: Add 1 again
A: If you add 1 to 2, the result would be 3.
Q: And add one again 
A: If you add 1 to 2, the result would be 3.

Obviously the answers here should be 2, 3, 4, 5 -- but it seems to only remember the first question, 1 + 1, and every subsequent question only uses that for context, when it should be using the entire thread.

The ChatGPT website handles this correctly, continuing to add 1 to the previous response.

**Comment by abielzulio** [comment]
Fixed on the 4/4 updated
