### ISSUE TITLE
GPT-4 is not listed in the Model list

### ISSUE THREAD

**Issue by EnixCoda** [abielzulio/chatgpt-raycast#34]
Hi, thank you for the excellent extensions!
I have enrolled ChatGPT Plus and have access to the GPT-4 model in ChatGPT web UI.
But when I try to switch the extension to GPT-4, it did not show up in the `Models`.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/7480839/229890136-4e6b189b-16b9-4f0f-b97d-61c949f03097.png">

I have tried regenerate API key, reinstall the extension, restart Raycast. None of them fixed this.

**Comment by abielzulio** [comment]
> Hi, thank you for the excellent extensions! I have enrolled ChatGPT Plus and have access to the GPT-4 model in ChatGPT web UI. But when I try to switch the extension to GPT-4, it did not show up in the `Models`.
> 
> <img alt="image" width="886" src="https://user-images.githubusercontent.com/7480839/229890136-4e6b189b-16b9-4f0f-b97d-61c949f03097.png">
> 
> I have tried regenerate API key, reinstall the extension, restart Raycast. None of them fixed this.

Hi!

Have you got the GPT-4 API access through https://openai.com/waitlist/gpt-4-api yet?

**Comment by EnixCoda** [comment]
No, did not know about this requirement.

Thank you!
