### ISSUE TITLE
Cannot select GPT-4

### ISSUE THREAD

**Issue by ashaney** [abielzulio/chatgpt-raycast#35]
This is an awesome extension! This issue is probably user error, but after putting in my API key, I am only seeing two GPT-3.5 models to choose from. I generated a new API key just to test and I still couldn't get it to work. Is there another step I am missing? Thanks for all your work on this :)

**Comment by abielzulio** [comment]
Hi!

Please refer to this: https://github.com/abielzulio/chatgpt-raycast#gpt-4

**Comment by ashaney** [comment]
Ah! That definitely explains it. Thank you 😁
