### ISSUE TITLE
I custom API url, not work

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [abielzulio/chatgpt-raycast#40]
I custom API url, not work：

![2023-10-11-100932](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2023/10/2023-10-11-100932.png)

It shows:

![2023-10-11-101402](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2023/10/2023-10-11-101402.png)

But, it works well on Chrome Extension (https://github.com/openai-translator/openai-translator):

![2023-10-11-101015](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2023/10/2023-10-11-101015.png)

Is there anything wrong?

**Comment by iodrift** [comment]
First of all, you do need to check the button that says "Change API Endpoint." But regardless, I just tested api.f2gpt.com myself:
```bash
curl https://api.f2gpt.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer [[REDACTED API KEY]]" \
  -d '{
    "messages": [
      { "role": "user", "content": "### Instruction:\n Please confirm receipt. \n\n ### Response:\n" }
    ],
    "stop": ["### Instruction:"],
    "temperature": 0.7,
    "max_tokens": -1,
    "stream": false
  }'
  ```


This returns `{"error":{"message":"提供的KEY有误，详情访问 f2api.com","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}%`      

Whereas the same curl command to https://open.openai.com/v1/chat/completions does work.

Do you have reason to trust this API? Not knowing anything about it, my guess is set up to collect people's API keys. I immediately revoked the API key I submitted to test it, and suggest you do the same unless you have a reason to trust it.

**Comment by sij-ai** [comment]
> I custom API url, not work：
> 
> ![2023-10-11-100932](https://camo.githubusercontent.com/c048952c2886c35fff18795afebdde45c7592d5a62c64a504e411e08a5f4c616/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4c617772656e63652d6f662d416e4b696e672f496d6742616e6b406d61696e2f696d674d442f323032332f31302f323032332d31302d31312d3130303933322e706e67)
> 
> It shows:
> 
> ![2023-10-11-101402](https://camo.githubusercontent.com/9548b0699474e1365a5b9286beefc94ad201eb3a86c961d47c471846835ec76e/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4c617772656e63652d6f662d416e4b696e672f496d6742616e6b406d61696e2f696d674d442f323032332f31302f323032332d31302d31312d3130313430322e706e67)
> 
> But, it works well on Chrome Extension (https://github.com/openai-translator/openai-translator):
> 
> ![2023-10-11-101015](https://camo.githubusercontent.com/b8f50c2561b31d95466317cfba88e0540e798cc6f1bf71f4e732c2624534a256/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4c617772656e63652d6f662d416e4b696e672f496d6742616e6b406d61696e2f696d674d442f323032332f31302f323032332d31302d31312d3130313031352e706e67)
> 
> Is there anything wrong?

First of all, you do need to check the button that says "Change API Endpoint." But regardless, I just tested api.f2gpt.com myself:

```bash
curl https://api.f2gpt.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer [[REDACTED API KEY]]" \
  -d '{
    "messages": [
      { "role": "user", "content": "### Instruction:\n Please confirm receipt. \n\n ### Response:\n" }
    ],
    "stop": ["### Instruction:"],
    "temperature": 0.7,
    "max_tokens": 200,
    "model":"gpt-4",
    "stream": false
  }'
  ```


This returns `{"error":{"message":"提供的KEY有误，详情访问 f2api.com","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}%`      

Whereas posting the same query to https://api.openai.com/v1/chat/completions does work.

Do you have reason to trust this API? Not knowing anything about it, my guess is set up to collect people's API keys. I immediately revoked the API key I submitted to test it, and suggest you do the same unless you have a reason to trust it.

**Comment by liaocaoxuezhe** [comment]
I send but still no result after mins, if I use in a wrong way?

![image](https://github.com/abielzulio/chatgpt-raycast/assets/48851266/5eca17e4-f141-467a-bf0d-3c7b8d2bc3f8)
