### ISSUE TITLE
Noob question... How do I install it ? 

### ISSUE THREAD

**Issue by thib5** [abielzulio/chatgpt-raycast#8]
Really sorry can't find the answer in google... how can i install it .. I thougt i did it I even enter my token and everything but when i try to use it the error " no js found" apear

Thanks

**Comment by jonbestdev** [comment]
> * type "Import extension" into raycast and find the above folder

There is no "Import extension", these are the import options now:

![image](https://user-images.githubusercontent.com/2657818/222785227-8d011bdc-bc1b-4b62-a49c-b3f2832657ce.png)

**Comment by altryne** [comment]
I think you may need this: 
![CleanShot 2023-03-03 at 15 05 55@2x](https://user-images.githubusercontent.com/463317/222838579-f957a07f-6ce2-46ae-891e-cc2e7b08c8a3.png)

**Comment by melalj** [comment]
Any updates since OpenAI is supporting now the ChatGPT API?

**Comment by abielzulio** [comment]
For everyone seeing this, to use it you need to `npm i` and `npm run dev` (for now). My main focus now is developing the extension as sleek as possible and probably making some breaking changes so please use it with your own caution.

Once it's all done, I'll submit it to the extension store so everyone can use it right away.

**Comment by rodrigo398** [comment]
> For everyone seeing this, to use it you need to `npm i` and `npm run dev` (for now). My main focus now is developing the extension as sleek as possible and probably making some breaking changes so please use it with your own caution.
> 
> Once it's all done, I'll submit it to the extension store so everyone can use it right away.

@abielzulio quick one: should the instructions be added to the README on how to install it manually?

**Comment by rodrigo398** [comment]
> > > For everyone seeing this, to use it you need to `npm i` and `npm run dev` (for now). My main focus now is developing the extension as sleek as possible and probably making some breaking changes so please use it with your own caution.
> > 
> > 
> > > 
> > 
> > 
> > > Once it's all done, I'll submit it to the extension store so everyone can use it right away.
> > 
> > 
> > @abielzulio quick one: should the instructions be added to the README on how to install it manually?
> 
> I'll submit the extension today so hopefully I don't need to do that.

@abielzulio that's awesome, thank you so much!. I'll probably be reaching out to you to make sure I can install the extension properly since I've done it but manually 👍
